version: "2"
services:
  nginx:
    build: ./nginx
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    ports:
      - "80:80"

  node1:
    build: ./nodejs
    environment:
      PORT: 4000
      SECRET: secret
      NODE_ENV: "production"
    ports:
      - "4000:4000"

  node2:
    build: ./nodejs
    environment:
      PORT: 4000
      SECRET: secret
      NODE_ENV: "production"
    ports:
      - "4001:4000"

  node3:
    build: ./nodejs
    environment:
      PORT: 4000
      SECRET: secret
      NODE_ENV: "production"
    ports:
      - "4002:4000"