version: "2"
networks:
  private:
services:
  nginx:
    build: ./nginx
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    ports:
      - "80:80"
    networks:
      - private

  node1:
    build: ./nodejs
    environment:
      EXPOSE: 4000
      SECRET: secret
      NODE_ENV: "production"
    networks:
      - private

  node2:
    build: ./nodejs
    environment:
      EXPOSE: 4000
      SECRET: secret
      NODE_ENV: "production"
    networks:
      - private

  node3:
    build: ./nodejs
    environment:
      EXPOSE: 4000
      SECRET: secret
      NODE_ENV: "production"
    networks:
      - private